[2022-05-06T15:04:26+0100] [MainThread] [I] [cwltool] Resolved 'md_list.cwl' to 'file:///gpfs01/scratch/mbexegc2/biobb_hpc_cwl_md_list/md_list.cwl'
[2022-05-06T15:04:56+0100] [MainThread] [W] [cwltool] Workflow checker warning:
md_list.cwl:240:79: Source 'output_cpt_file' of type ["null", "File"] may be incompatible
md_list.cwl:253:7:    with sink 'external_files' of type {"type": "array", "items": "File"}
                      source has linkMerge method merge_flattened
                      pickValue is: all_non_null
md_list.cwl:205:7:  'input_ndx_path' is not an input parameter of
                    file:///gpfs01/scratch/mbexegc2/biobb_hpc_cwl_md_list/biobb/biobb_adapters/cwl/biobb_md/gromacs/grompp.cwl,
                    expected config, input_cpt_path, input_gro_path, input_top_zip_path
md_list.cwl:183:7:  'input_ndx_path' is not an input parameter of
                    file:///gpfs01/scratch/mbexegc2/biobb_hpc_cwl_md_list/biobb/biobb_adapters/cwl/biobb_md/gromacs/grompp.cwl,
                    expected config, input_gro_path, input_top_zip_path
md_list.cwl:229:7:  'input_ndx_path' is not an input parameter of
                    file:///gpfs01/scratch/mbexegc2/biobb_hpc_cwl_md_list/biobb/biobb_adapters/cwl/biobb_md/gromacs/grompp.cwl,
                    expected config, input_cpt_path, input_gro_path, input_top_zip_path
[2022-05-06T15:04:56+0100] [MainThread] [I] [toil.job] Saving graph of 2 jobs, 2 new
[2022-05-06T15:04:56+0100] [MainThread] [I] [toil.job] Processing job 'ResolveIndirect' kind-ResolveIndirect/instance-ze9j6t2f v0
[2022-05-06T15:04:56+0100] [MainThread] [I] [toil.job] Processing job 'CWLWorkflow' kind-CWLWorkflow/instance-miatoaej v0
[2022-05-06T15:04:57+0100] [MainThread] [I] [toil] Running Toil version 5.6.0-c34146a6437e4407a61e946e968bcce67a0ebbca on host login02.csf4.local.
[2022-05-06T15:04:58+0100] [MainThread] [I] [toil.worker] Redirecting logging to /gpfs01/scratch/mbexegc2/biobb_hpc_cwl_md_list/workdir/1d22f79a49de5ce89ff24ecb4ffa639b/fa0d/worker_log.txt
[2022-05-06T15:04:59+0100] [MainThread] [I] [toil.leader] 2 jobs are running, -1 jobs are issued and waiting to run
[2022-05-06T15:05:03+0100] [MainThread] [W] [toil.leader] A result seems to already have been processed for job 0
[2022-05-06T15:06:45+0100] [MainThread] [W] [toil.leader] Job failed with exit value 127: 'CWLWorkflow' kind-CWLWorkflow/instance-miatoaej v1
Exit reason: None
[2022-05-06T15:06:45+0100] [MainThread] [W] [toil.leader] No log file is present, despite job failing: 'CWLWorkflow' kind-CWLWorkflow/instance-miatoaej v2
[2022-05-06T15:06:45+0100] [MainThread] [W] [toil.leader] The batch system left a non-empty file /gpfs01/scratch/mbexegc2/biobb_hpc_cwl_md_list/workdir/toil_305c10a6-888c-4a16-9bf0-82fb88f27520.1.326706.err.log:
[2022-05-06T15:06:45+0100] [MainThread] [W] [toil.leader] Log from job "kind-CWLWorkflow/instance-miatoaej" follows:
=========>
	/tmp/slurmd/job326706/slurm_script: line 4: _toil_worker: command not found
<=========
[2022-05-06T15:06:45+0100] [MainThread] [W] [toil.leader] The batch system left an empty file /gpfs01/scratch/mbexegc2/biobb_hpc_cwl_md_list/workdir/toil_305c10a6-888c-4a16-9bf0-82fb88f27520.1.326706.out.log
[2022-05-06T15:06:45+0100] [MainThread] [W] [toil.job] Due to failure we are reducing the remaining try count of job 'CWLWorkflow' kind-CWLWorkflow/instance-miatoaej v2 with ID kind-CWLWorkflow/instance-miatoaej to 1
[2022-05-06T15:06:45+0100] [MainThread] [W] [toil.job] We have increased the default memory of the failed job 'CWLWorkflow' kind-CWLWorkflow/instance-miatoaej v2 to 2147483648 bytes
[2022-05-06T15:06:45+0100] [MainThread] [W] [toil.job] We have increased the disk of the failed job 'CWLWorkflow' kind-CWLWorkflow/instance-miatoaej v2 to the default of 2147483648 bytes
[2022-05-06T15:06:46+0100] [MainThread] [I] [toil.worker] Redirecting logging to /gpfs01/scratch/mbexegc2/biobb_hpc_cwl_md_list/workdir/1d22f79a49de5ce89ff24ecb4ffa639b/cefa/worker_log.txt
[2022-05-06T15:06:48+0100] [MainThread] [I] [toil.leader] Issued job 'CWLJob' md_list.cwl.step1_pdb2gmx.pdb2gmx.cwl kind-CWLJob/instance-68g01jxs v1 with job batch system ID: 3 and cores: 1, disk: 2.0 Gi, and memory: 1.0 Gi
[2022-05-06T15:07:21+0100] [MainThread] [W] [toil.leader] Job failed with exit value 127: 'CWLJob' md_list.cwl.step1_pdb2gmx.pdb2gmx.cwl kind-CWLJob/instance-68g01jxs v1
Exit reason: None
[2022-05-06T15:07:21+0100] [MainThread] [W] [toil.leader] No log file is present, despite job failing: 'CWLJob' md_list.cwl.step1_pdb2gmx.pdb2gmx.cwl kind-CWLJob/instance-68g01jxs v1
[2022-05-06T15:07:21+0100] [MainThread] [W] [toil.leader] The batch system left a non-empty file /gpfs01/scratch/mbexegc2/biobb_hpc_cwl_md_list/workdir/toil_305c10a6-888c-4a16-9bf0-82fb88f27520.3.326708.err.log:
[2022-05-06T15:07:21+0100] [MainThread] [W] [toil.leader] Log from job "kind-CWLJob/instance-68g01jxs" follows:
=========>
	/tmp/slurmd/job326708/slurm_script: line 4: _toil_worker: command not found
<=========
[2022-05-06T15:07:21+0100] [MainThread] [W] [toil.leader] The batch system left an empty file /gpfs01/scratch/mbexegc2/biobb_hpc_cwl_md_list/workdir/toil_305c10a6-888c-4a16-9bf0-82fb88f27520.3.326708.out.log
[2022-05-06T15:07:21+0100] [MainThread] [W] [toil.job] Due to failure we are reducing the remaining try count of job 'CWLJob' md_list.cwl.step1_pdb2gmx.pdb2gmx.cwl kind-CWLJob/instance-68g01jxs v1 with ID kind-CWLJob/instance-68g01jxs to 1
[2022-05-06T15:07:21+0100] [MainThread] [W] [toil.job] We have increased the default memory of the failed job 'CWLJob' md_list.cwl.step1_pdb2gmx.pdb2gmx.cwl kind-CWLJob/instance-68g01jxs v1 to 2147483648 bytes
[2022-05-06T15:07:21+0100] [MainThread] [I] [toil.leader] Issued job 'CWLJob' md_list.cwl.step1_pdb2gmx.pdb2gmx.cwl kind-CWLJob/instance-68g01jxs v2 with job batch system ID: 4 and cores: 1, disk: 2.0 Gi, and memory: 2.0 Gi
[2022-05-06T15:07:57+0100] [MainThread] [W] [toil.leader] Job failed with exit value 127: 'CWLJob' md_list.cwl.step1_pdb2gmx.pdb2gmx.cwl kind-CWLJob/instance-68g01jxs v2
Exit reason: None
[2022-05-06T15:07:57+0100] [MainThread] [W] [toil.leader] No log file is present, despite job failing: 'CWLJob' md_list.cwl.step1_pdb2gmx.pdb2gmx.cwl kind-CWLJob/instance-68g01jxs v2
[2022-05-06T15:07:57+0100] [MainThread] [W] [toil.leader] The batch system left a non-empty file /gpfs01/scratch/mbexegc2/biobb_hpc_cwl_md_list/workdir/toil_305c10a6-888c-4a16-9bf0-82fb88f27520.4.326709.err.log:
[2022-05-06T15:07:57+0100] [MainThread] [W] [toil.leader] Log from job "kind-CWLJob/instance-68g01jxs" follows:
=========>
	/tmp/slurmd/job326709/slurm_script: line 4: _toil_worker: command not found
<=========
[2022-05-06T15:07:58+0100] [MainThread] [W] [toil.leader] The batch system left an empty file /gpfs01/scratch/mbexegc2/biobb_hpc_cwl_md_list/workdir/toil_305c10a6-888c-4a16-9bf0-82fb88f27520.4.326709.out.log
[2022-05-06T15:07:58+0100] [MainThread] [W] [toil.job] Due to failure we are reducing the remaining try count of job 'CWLJob' md_list.cwl.step1_pdb2gmx.pdb2gmx.cwl kind-CWLJob/instance-68g01jxs v2 with ID kind-CWLJob/instance-68g01jxs to 0
[2022-05-06T15:07:58+0100] [MainThread] [W] [toil.leader] Job 'CWLJob' md_list.cwl.step1_pdb2gmx.pdb2gmx.cwl kind-CWLJob/instance-68g01jxs v3 is completely failed
[2022-05-06T15:08:04+0100] [MainThread] [I] [toil.leader] Finished toil run with 2 failed jobs.
[2022-05-06T15:08:04+0100] [MainThread] [I] [toil.leader] Failed jobs at end of the run: 'CWLWorkflow' kind-CWLWorkflow/instance-miatoaej v3 'CWLJob' md_list.cwl.step1_pdb2gmx.pdb2gmx.cwl kind-CWLJob/instance-68g01jxs v3
Traceback (most recent call last):
  File "/gpfs01/scratch/mbexegc2/biobb_hpc_cwl_md_list/venv/bin/toil-cwl-runner", line 8, in <module>
    sys.exit(main())
  File "/gpfs01/scratch/mbexegc2/biobb_hpc_cwl_md_list/venv/lib/python3.9/site-packages/toil/cwl/cwltoil.py", line 3486, in main
    outobj = toil.start(wf1)
  File "/gpfs01/scratch/mbexegc2/biobb_hpc_cwl_md_list/venv/lib/python3.9/site-packages/toil/common.py", line 951, in start
    return self._runMainLoop(rootJobDescription)
  File "/gpfs01/scratch/mbexegc2/biobb_hpc_cwl_md_list/venv/lib/python3.9/site-packages/toil/common.py", line 1273, in _runMainLoop
    return Leader(config=self.config,
  File "/gpfs01/scratch/mbexegc2/biobb_hpc_cwl_md_list/venv/lib/python3.9/site-packages/toil/leader.py", line 289, in run
    raise FailedJobsException(self.jobStore, failed_jobs, exit_code=self.recommended_fail_exit_code)
toil.leader.FailedJobsException: The job store '/gpfs01/scratch/mbexegc2/biobb_hpc_cwl_md_list/jobstore/test_2022-05-06_15-04' contains 2 failed jobs: 'CWLWorkflow' kind-CWLWorkflow/instance-miatoaej v3, 'CWLJob' md_list.cwl.step1_pdb2gmx.pdb2gmx.cwl kind-CWLJob/instance-68g01jxs v3
